using Microsoft.Extensions.Options;
using MongoDB.Driver;
using MongoDbBookstoreApi.Models;
using System.Diagnostics;

namespace MongoDbBookstoreApi.Services
{
    public class MongoMediaRepository : IMediaRepository
    {
        private readonly IMongoCollection<MediaFile> _collection;

        public MongoMediaRepository(IOptions<BookStoreDatabaseSettings> bookStoreDatabaseSettings)
        {
            var mongoClient = new MongoClient(
                bookStoreDatabaseSettings.Value.ConnectionString);

            var mongoDatabase = mongoClient.GetDatabase(
                bookStoreDatabaseSettings.Value.DatabaseName);
            _collection = mongoDatabase.GetCollection<MediaFile>("MediaFiles");
        }

        //public async Task<string> SaveAsync(MediaFile media)
        //{
        //    await _collection.InsertOneAsync(media);
        //    return media.Id!;
        //}

        public async Task<String> UpsertAsync(MediaFile media)
        {
            // Filter to find the existing document by its ID
            var filter = Builders<MediaFile>.Filter.Eq(m => m.Id, media.Id);

            // Replace the document if found; otherwise, insert it
            var options = new ReplaceOptions { IsUpsert = true };

            var result = await _collection.ReplaceOneAsync(filter, media, options);
            // 1. If we inserted a new doc, return the new ID generated by Mongo
            if (result.UpsertedId != null)
            {
                return result.UpsertedId.ToString();
            }
            return media.Id!;
        }

        public async Task<MediaFile?> GetByIdAsync(string id)
        {
            try
            {
                return await _collection.Find(m => m.Id == id).FirstOrDefaultAsync();
            }
            catch (Exception ex)
            { 
                Debug.WriteLine($"Error retrieving media file with ID {id}: {ex.Message}");
                throw;
            }
        }
    }
}
